# Problem 15.2: Identifying Course Combinations
The Institute for Statistics Education at Statistics.com offers online courses in statistics and analytics, and is seeking information that will help in packaging and sequencing courses.  Consider the data in the file _CourseTopics.csv_, the first few rows of which are shown in the Table. These data are for purchases of online statistics courses at Statistics.com. Each row represents the courses attended by a single customer.
The firm wishes to assess alternative sequencings and bundling of courses. Use association rules to analyze these data, and interpret several of the resulting rules.

In [1]:
import mlba
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
df = mlba.load_data('CourseTopics.csv')
df.head()

   Intro  DataMining  Survey  Cat Data  Regression  Forecast  DOE  SW
0      1           1       0         0           0         0    0   0
1      0           0       1         0           0         0    0   0
2      0           1       0         1           1         0    0   1
3      1           0       0         0           0         0    0   0
4      1           1       0         0           0         0    0   0

In [4]:
itemsets = apriori(df, min_support=0.01, use_colnames=True)

rules = association_rules(itemsets, metric='confidence', min_threshold=0.1)

r = rules.sort_values(by='lift', ascending=False)

print(r.drop(columns=['antecedent support', 'consequent support', 'conviction']).head(6))

                antecedents             consequents   support  confidence  \
318        (Regression, SW)            (DOE, Intro)  0.019178    0.350000
319            (DOE, Intro)        (Regression, SW)  0.019178    0.411765
321             (Intro, SW)       (Regression, DOE)  0.019178    0.200000
316       (Regression, DOE)             (Intro, SW)  0.019178    0.636364
249     (Intro, DataMining)  (Regression, Forecast)  0.013699    0.250000
248  (Regression, Forecast)     (Intro, DataMining)  0.013699    0.357143

         lift  representativity  leverage  zhangs_metric   jaccard  certainty  \
318  7.514706               1.0  0.016626       0.917184  0.233333   0.318247
319  7.514706               1.0  0.016626       0.909278  0.233333   0.377664
321  6.636364               1.0  0.016288       0.939394  0.179487   0.175141
316  6.636364               1.0  0.016288       0.875706  0.179487   0.597796
249  6.517857               1.0  0.011597       0.895652  0.172414   0.220085
248  6.517857               1.0  0.011597       0.880342  0.172414   0.319876

     kulczynski
318    0.380882
319    0.380882
321    0.418182
316    0.418182
249    0.303571
248    0.303571

C:\Users\samsc\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [5]:
single_rules = rules[[len(c) == 1 for c in rules['consequents']]]

(single_rules.sort_values(by='lift', ascending=False).drop(columns=['antecedent support', 'consequent support', 'conviction']).head(6))

,antecedents,consequents,support,confidence,lift,representativity,leverage,zhangs_metric,jaccard,certainty,kulczynski
243,"(Regression, Intro, Forecast)",(DataMining),0.013699,0.714286,4.010989,1.0,0.010283,0.765363,0.074627,0.652381,0.395604
263,"(DOE, Intro, Survey)",(Cat Data),0.010959,0.800000,3.842105,1.0,0.008107,0.750000,0.051948,0.747405,0.426316
235,"(Cat Data, Intro, DataMining)",(Regression),0.016438,0.750000,3.601974,1.0,0.011875,0.738562,0.076923,0.684256,0.414474
252,"(Cat Data, Intro, Survey)",(Forecast),0.013699,0.500000,3.578431,1.0,0.009871,0.740845,0.089286,0.418790,0.299020
242,"(Regression, Intro, DataMining)",(Forecast),0.013699,0.500000,3.578431,1.0,0.009871,0.740845,0.089286,0.418790,0.299020
312,"(Regression, DOE, Intro)",(SW),0.019178,0.777778,3.504801,1.0,0.013706,0.732745,0.084337,0.714397,0.432099